### ISSUE TITLE
Hints on the macro for case generation?

### ISSUE THREAD

**Issue by codepope** [CrazyRobMiles/PICO-Chord-keyboard#1]
Could there be some hints on how the macro works? 

Background: I was going to print the default STL but it's mm too wide on the edges for my Adventurer 3. So I settled down to figure out how the macro assembles things but I couldn't figure out how the components worked together to get the overall size (which I think comes as a function of the the keylayout and insets). So I would love to see some notes on the dependencies inside there.... (before I panic and look for a bigger printer :) )

**Comment by CrazyRobMiles** [comment]
Hi. Good point. I've added extra details about changing the size and position of the keys.

**Comment by codepope** [comment]
Thanks! Will give the info a run tonight!

**Comment by codepope** [comment]
Actually, already have and sized the box down to something I can print. So that's great.
